config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get "posts/mypage"        => "posts#mypage"
  post "posts/create"       => "posts#create"
  post "posts/:id/update"   => "posts#update"
  # post "posts/:id/destroy" => "posts#destroy"
  post "posts/:id/strength" => "posts#strength"
  post "posts/:id/weakness" => "posts#weakness"
  root to: 'posts#index'
  get  "/signup"            => "users#new"
  post  "/signup"            => "users#create"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :posts
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(
      title: params[:title], 
      expect: params[:expect], 
      actual: params[:actual],
      strength: 0)
    @post.save
    redirect_to posts_url
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    @post.title= params[:title]
    @post.expect= params[:expect]
    @post.actual= params[:actual]
    @post.save
    redirect_to posts_url
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    # head :no_content
    # redirect_to posts_url
  end

  def strength
    @post = Post.find_by(id: params[:id])
    @post.strength = 1
    @post.save
    redirect_to posts_mypage_url
  end
  
  def weakness
    @post = Post.find_by(id: params[:id])
    @post.strength = 2
    @post.save
    redirect_to posts_mypage_url
  end

  def mypage
    @strengths = Post.where(strength: 1)
    @weaknesses = Post.where(strength: 2)
    @normals = Post.where(strength: 0)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user    
    else
      flash.now[:danger] = 'Invalid email/password combination' # 本当は正しくない
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kizitu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <div class="btn btn-outline-warning"><%= link_to("ユーザー登録", signup_path ) %></div>
      </header>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/posts/destroy.js.erb
document.querySelector("#post-<%= @post.id %>").style.display = 'none';

app/views/posts/edit.html.erb
<h1>編集画面</h1>

<%= link_to("一覧", "/") %>

<%= form_tag("/posts/#{@post.id}/update") do %>
  <input type="text" name="title" value="<%= @post.title %>">
  <input type="text" name="expect" value="<%= @post.expect %>">
  <input type="text" name="actual" value="<%= @post.actual %>">
  <input type="submit" value="編集">
<% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>

<div class="btn btn-outline-info"><%= link_to("新規投稿", "/posts/new") %></div>
<div class="btn btn-outline-warning"><%= link_to("マイページ", "/posts/mypage") %></div>


<%= search_form_for @q ,url: posts_path, class: 'mb-5' do |f| %>
  <div class="form-group row">
    <%= f.label :title_cont, '名称', class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.search_field :title_cont ,class: 'form_control' %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.submit class: 'btn btn-outline-primary' %>
  </div>
<% end %>

<div class="mb-3">
  <%= paginate @posts %>
  <%= page_entries_info @posts %>
</div>


<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"><%= sort_link(@q, :title) %></th>
      <th scope="col" class="text-success">期待する成果</th>
      <th scope="col" class="text-secondary">実際の成果</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
    <tr id="post-#{post.id}">
      <th scope="row"><%= post.id %></th>
      <td><%= link_to(post.title, "/posts/#{post.id}") %></td>
      <td><%= post.expect %></td>
      <td><%= post.actual %></td>
      <td><%= link_to("編集", edit_post_path(post), class: 'btn btn-success') %></td>
      <td><%= link_to("削除", post, method: :delete, remote: true, data: { confirm: "#{post.title}を削除します。よろしいですか？" }, class: 'btn btn-danger delete') %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/mypage.html.erb
<h1>マイページ</h1>
<%= link_to("一覧", "/") %>

<div class="container">
<div class="row">
<div class="col-sm">
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col" class="bg-warning">得意</th>
    </tr>
  </thead>
  <tbody>
    <% @strengths.each do |strength| %>
    <tr>
      <th scope="row"><%= strength.id %></th>
      <td><%= link_to(strength.title, "/posts/#{strength.id}") %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="col-sm">
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col" class="bg-light">不得意</th>
    </tr>
  </thead>
  <tbody>
    <% @weaknesses.each do |weakness| %>
    <tr>
      <th scope="row"><%= weakness.id %></th>
      <td><%= link_to(weakness.title, "/posts/#{weakness.id}") %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="col-sm">
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col" class="bg-white">普通</th>
    </tr>
  </thead>
  <tbody>
    <% @normals.each do |normal| %>
    <tr>
      <th scope="row"><%= normal.id %></th>
      <td><%= link_to(normal.title, "/posts/#{normal.id}") %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/posts/new.html.erb
<h1>新規投稿</h1>

<%= link_to("一覧", "/") %>

<%= form_tag("/posts/create") do %>
  <input type="text" name="title" placeholder="タイトル">
  <input type="text" name="expect" placeholder="期待する成果">
  <input type="text" name="actual" placeholder="実際の成果">
  <input type="submit" value="投稿">
<% end %>

app/views/posts/show.html.erb
<h1>詳細画面</h1>

<%= link_to("一覧", posts_path ) %>
<%= link_to("編集", edit_post_path ) %>


<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">タイトル</th>
      <th scope="col">期待する成果</th>
      <th scope="col">実際の成果</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row"><%= @post.id %></th>
      <td><%= @post.title %></td>
      <td><%= @post.expect %></td>
      <td><%= @post.actual %></td>
    </tr>
  </tbody>
</table>

<div class="text-center pt-5">
  <div class="btn btn-lg btn-default mr-5"><%= link_to("不得意","/posts/#{@post.id}/weakness", {method: "post"}) %></div>
  <div class="btn btn-lg btn-default ml-5"><%= link_to("得意","/posts/#{@post.id}/strength", {method: "post"}) %></div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>